---
title: "Homework"
author: "a104260048"
date: "2018/10/5"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Notes on the YAML header
 ¡E Be sure to change the title and author fields
  
 ¡E  The date is automatically set to the current day when knitting
  
 ¡E  The header-includes portion loads a personal sheet of LaTeX macros. I recommend making one of these as well as it can    greatly speed up the time to input math. See my personal macro file hayesmacros.sty as a starting point. If you aren't   going to load a \LaTeX macro file, remove those lines.
    ¡Chayesmacros.sty needs to be in the same folder as this file

#Problem 1
Here is a [link](https://adv-r.hadley.nz/). Your homework goes here.

Briefly, some of the custom latex macros: $y = \b x + \e$. Also, some code:

  fit <- lm(hp ~ ., mtcars)
  au <- broom::augment(fit)

  au %>% 
    gather(x, val, -contains(".")) %>%
    ggplot(aes(val, .resid)) +
    geom_point() +
    facet_wrap(~x, scales = "free")
    
Yet more text, and another code section:

  knitr::kable(head(select(au, 1:5)))

#Code
 #this R markdown chunk generates a code appendix